### ISSUE TITLE
Не уловил сути

### ISSUE THREAD

**Issue by andrew-svirin** [execut/yii2-dependencies#1]
Решает ли данный функционал вызовы методов сервисов из другого модуля?

**Comment by execut** [comment]
Здравствуйте! Примеры использования этого пакета можно увидеть в других моих пакетах. Вот, например, есть пакет для управления страницами [execut\yii2-pages](https://github.com/execut/yii2-pages/). У него есть модуль [execut\pages\Module.php](https://github.com/execut/yii2-pages/blob/master/Module.php). Данный модуль использует поведение PluginBehavior из yii2-dependencies. И за счёт этого у данного модуля появляется возможность подключать плагины со стороны других модулей для расширения его функционала. Примеры реализации плагинов для этого модуля можете найти [здесь](https://github.com/execut/yii2-pages/tree/master/plugin).

**Comment by execut** [comment]
Таким образом мы можем разграничить два модуля и расширять их независимо через плагины. Таким образом можно и сервисы другого модуля цеплять как вы хотите

**Comment by andrew-svirin** [comment]
Спасибо за расширенный ответ )

**Comment by andrew-svirin** [comment]
Такой вопрос, а плагин, знает что он имплементирует интерфейс https://github.com/execut/yii2-pages/blob/master/Plugin.php  и для кого он имплементирует?

**Comment by execut** [comment]
Пожалуйста)
Да, получается реализация плагина - это тот класс, который знает про все учавствующие модули. С опытом я пришёл к выводу, что лучше такие плагины выносить вообще в отдельный пакет. Так не нужно городить код в модуле, который не относится к нему. Ещё не будет проблем с миграциями. Вот пример такого пакета: https://github.com/execut/yii2-pages-alias. Это интеграционный модуль, который связывает yii2-alias и yii2-pages. Остальные плагины не было пока возможности перенести.
